### ISSUE TITLE
【プロジェクトの途中でカスタムのUserModelに移行する】

### ISSUE THREAD

**Issue by Kaito-a-bit** [Kaito-a-bit/twitter_clone_app#4]
○該当ブランチ
　#2 (最新状態はpush済み)

○やりたいこと
- 最終課題で使用するUserモデルを`AbstractBaseUser`を拡張する形でカスタムしたい
- プロジェクト作成後のモデル変更は若干難しく、データベースを一旦削除してmigrationsを再実行する必要がある

上記を達成する為に、以下の手順で実行しようとした。
参考: 
[【Django】独自ユーザーモデルの作成（カスタムUserモデル：AbstractBaseUser）](https://office54.net/python/django/model-custom-user)
[Changing to a custom user model mid-project](https://docs.djangoproject.com/en/2.1/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project)
[How to Switch to a Custom Django User Model Mid-Project](https://www.caktusgroup.com/blog/2019/04/26/how-switch-custom-django-user-model-mid-project/)
1. カスタムした`User`モデルを作成（`username`, `email`, `password`, `birthday(追加したいフィールド)`）
2. カスタムした`UserManager`モデルを作成する
3. 認証モデルを変更する
4. DB削除・マイグレーション実行（要調査）

3までは実行済みで4を実行する前に[このサイト](https://marsquai.com/745ca65e-e38b-4a8e-8d59-55421be50f7e/05f253f8-c11b-4c91-8091-989eb2600a7b/229d6ef3-1ba3-4e16-bdd7-c5f01c6dfb12/#h3-711aa683-7b15-4467-ac8e-7b94c4191a8c-761724b0-9f59-4017-886b-9d3820d06618)を参考に**データベースのバックアップ**をとろうとした。

**Comment by Akinori13** [comment]
- 変更前のモデルをA
- 変更後のモデルをB

とします。
- DBはモデルAにより作られています。
- jsonファイルを生成する時はモデルBを参考にします。

すると、バックアップ作成時はモデルBを参考にしてるので、DBに存在しないbirthdayフィールドにアクセスし、エラーが発生するという状況かと予測されます。（つまりDBのフィールドとUserモデルのフィールドが一致していない状態。）

モデルを以前の状態に書き直して実行してみてください。

**Comment by Akinori13** [comment]
birthdayフィールドが定義されていないです。まずは`()`つけましょう！

**Comment by Kaito-a-bit** [comment]
> * 変更前のモデルをA
> * 変更後のモデルをB
> 
> とします。
> 
> * DBはモデルAにより作られています。
> * jsonファイルを生成する時はモデルBを参考にします。
> 
> バックアップ作成時はモデルBを参照にしているので、DBに存在しないtableにアクセスし、エラーが発生するという状況かと予測されます。

まさにこうなりました。ありがとうございます。
**変更後のモデル**に対してのマイグレーションはまだ実行されていないので、この後の手順としては
- DBの削除
- migrationを実行
の二つだと認識しているのですがあっていますでしょうか？

**Comment by Akinori13** [comment]
> > * 変更前のモデルをA
> > * 変更後のモデルをB
> > 
> > とします。
> > 
> > * DBはモデルAにより作られています。
> > * jsonファイルを生成する時はモデルBを参考にします。
> > 
> > バックアップ作成時はモデルBを参照にしているので、DBに存在しないtableにアクセスし、エラーが発生するという状況かと予測されます。
> 
> まさにこうなりました。ありがとうございます。 **変更後のモデル**に対してのマイグレーションはまだ実行されていないので、この後の手順としては
> 
> * DBの削除
> * migrationを実行
>   の二つだと認識しているのですがあっていますでしょうか？

バックアップ取れているならokです
