### ISSUE TITLE
【'AnonymousUser' object has no attribute '_meta'】

### ISSUE THREAD

**Issue by Kaito-a-bit** [Kaito-a-bit/twitter_clone_app#5]
最新状態はpush済です。
○経緯
- ユーザモデルをAbstractBaseUserを拡張する形でカスタムのモデルに変更した
- カスタムモデルを使用する際には、フォームをいじる必要があるらしいのでフォームを再度作成した
- フォームの作り直しが終わったので、ユーザ登録が機能するかどうかを確認しようとしたところこのエラーに当たった。

○調べたこと
- エラーメッセージを調べてみた
　→このエラーに当たる原因が複数あるようで、参考になるものがなかった
- エラーが出ているのが`login`の部分なので`authenticate`と`login`について調べた
　→`login`に渡すインスタンスに関係がありそうだった。

```python
user = authenticate(username=username, password=password)
login(self.request, user)
self.object = user
```
としている所を以下のようにしたが、違うエラーが出た。
ここではlogin関数で引数にとっている`user`は一行上で宣言したものを指定する必要があると認識している。
```
user = authenticate(username=username, password=password)
login(self.request, User)
self.object = user
```

○エラーページ
<img width="1920" alt="スクリーンショット 2022-02-21 13 52 14" src="https://user-images.githubusercontent.com/73689418/154891795-2f0af823-0ea8-416a-801c-4257b7dad9eb.png">

○Traceback
```Python 
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/signup/

~~~

Traceback (most recent call last):
  File "/Users/araikaito/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/araikaito/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/araikaito/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/araikaito/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/araikaito/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/Users/araikaito/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/araikaito/Desktop/Shinonome/Backend/twitter_clone_app/user/views.py", line 31, in form_valid
    login(self.request, user)
  File "/Users/araikaito/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 129, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "/Users/araikaito/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/utils/functional.py", line 247, in inner
    return func(self._wrapped, *args)

Exception Type: AttributeError at /signup/
Exception Value: 'AnonymousUser' object has no attribute '_meta'

```

**Comment by Akinori13** [comment]
authenticate()は、認証されたユーザーを返します。
しかし、この時点ではユーザー登録がなされていません。
authenticateより前にユーザー登録をしましょう。

**Comment by Kaito-a-bit** [comment]
> authenticate()は、認証されたユーザーを返します。 しかし、この時点ではユーザー登録がなされていません。 authenticateより前にユーザー登録をしましょう。

```python
    user = User.objects._create_user(username, email, password)
    user = form.save()
```
としてユーザ登録する機能を追加しました。
するとまだ存在しないははずにも関わらず、emailが重複しているという旨のエラーメッセージが出てきました。上記の処理でユーザ登録が重複しているとは考えにくいのですが、何かヒントがあれば教えて頂きたいです。

**Comment by TAK848** [comment]
1. `SignUpView`で`form_valid`をオーバーライドしていますが，継承元のの処理を呼び出し忘れているので，頭に
```python
    def form_valid(self, form):
        valid = super().form_valid(form)
        ...
```
みたいにつけましょう。そしてこの間に追加でしたい処理（この場合はログイン）
`form_valid`の`return`も，このデフォルトの返り値を
```python
        return valid
```
として返せばOKだと思います。ResponseRedirectをここに書かずとも，success_urlによって自動で成功時に飛びます。
2. `authenticate`関数は，認証用のバックエンドを作成する必要があり，複雑みたいです（適当なこと言ってたらすみません）。 https://django.kurodigi.com/customize-auth-backend/
実際，`print(user)`とすると，`username`と`password`を取った認証方法は存在しないため失敗し，`None`が帰ってきていることが確認できます。
CreateViewによって作られたユーザーオブジェクトは，`form.object`に格納されているので，こいつをloginの第二引数に入れてやればログインもうまくいくはずです。

**Comment by TAK848** [comment]
この件のフローの参考: https://www.reddit.com/r/djangolearning/comments/gwflu0/how_to_access_the_model_class_object_in_form/

その中のdiscussionの https://www.reddit.com/r/djangolearning/comments/gwflu0/comment/fsuwrsm/?utm_source=share&utm_medium=web2x&context=3 とか

validationの流れを，[公式doc](https://docs.djangoproject.com/ja/3.2/ref/forms/validation/)や，もし持っていれば，[akiyokoさんの本](https://www.amazon.co.jp/gp/product/B07GK7BWB7/)の8.2節，8.6節で確認してみると良いかもしれません。

**Comment by TAK848** [comment]
> > authenticate()は、認証されたユーザーを返します。 しかし、この時点ではユーザー登録がなされていません。 authenticateより前にユーザー登録をしましょう。
> 
> ```python
>     user = User.objects._create_user(username, email, password)
>     user = form.save()
> ```
> 
> としてユーザ登録する機能を追加しました。 するとまだ存在しないははずにも関わらず、emailが重複しているという旨のエラーメッセージが出てきました。上記の処理でユーザ登録が重複しているとは考えにくいのですが、何かヒントがあれば教えて頂きたいです。

返信できてませんでした。すみません
1行目でuserは正常に作成されますが，これだとcreateViewに全く関係なく作られています。
2行目で，form経由で全く同じデータで保存しているため，2重登録になっています。上の僕のコメントの1で書いたsuper().form_valid(form)を利用すると，form.save()までやってくれます [参考](https://hiroronn.hatenablog.jp/entry/20190308/1552048025#%E4%BD%99%E8%AB%87%E4%BF%9D%E5%AD%98%E5%87%A6%E7%90%86%E3%81%8C%E5%91%BC%E3%81%B0%E3%82%8C%E3%82%8B%E3%82%BF%E3%82%A4%E3%83%9F%E3%83%B3%E3%82%B0)

**Comment by Kaito-a-bit** [comment]
追記: `UserCreationForm`内の`Meta`クラスは何をしているのか
参考: [UserCreationForm with Multiple fields In Django.](https://dev.to/yahaya_hk/usercreation-form-with-multiple-fields-in-django-ek9)

メタクラスの機能は2つ
- どのモデルを使用しているのかを明示する
- モデルの中のどのフィールドをフォームの中に含めたいかを指定する

`UserCreationForm`が本来持っているフィールドは`username`, `password1`, `password2`だが、追加したいフィールドがあれば`UserCreationForm`を継承しているクラス内で追記する。

**Comment by Kaito-a-bit** [comment]
- `forms.py`と`models.py`の棲み分けは何か
`UserCreationForm`は新しいユーザを作成するフォーム。
`UserCreationForm`がデフォルトで持っている**フィールド**は、`username`, `password1`, `password2`。
`fields`では**使用するモデルの中でフォームを作成してほしいカラムを指定する。**
