### ISSUE TITLE
【認証バックエンドを通らない】

### ISSUE THREAD

**Issue by Kaito-a-bit** [Kaito-a-bit/twitter_clone_app#8]
○経緯・問題
- 最終課題のユーザ登録機能を作成する中でdjangoの認証バックエンドを通す必要があった
- `authenticate(username=email)`として認証したいが要件として**username**のフィールドは必要
- そもそも`username`のフィールドを残したまま`email`を`username`として認証することは可能？

**Comment by Kaito-a-bit** [comment]
○`username`を`email`として認証する方法を調べていて出てきた方法は下記
- ユーザーネームのカラムを持たないカスタムしたユーザモデルを作成
- `models`内で`USERNAME_FIELD="email"`としてユーザの識別子をemailとする
- authenticate(usename=email)で認証する

最終課題の要件としてユーザネームは必要なので、ユーザネームのカラムを残したままemailで認証をしたい

**Comment by Kaito-a-bit** [comment]
- [comment](https://github.com/Kaito-a-bit/twitter_clone_app/pull/2#issuecomment-1062354197)

- `password1`でも試行したが依然、パスワードの取得ができていないことが確認できた。
↓ログイン時の`print`文で`None`が返ってきている。  
<img width="810" alt="スクリーンショット 2022-03-09 15 52 24" src="https://user-images.githubusercontent.com/73689418/157388120-64a45f9d-017c-4dc9-9381-2cdab0816de1.png">

- 一応migrationを確認したが、問題はなかった。

**Comment by fumiharun11** [comment]
添付のスクリーンショットについて、formから取得しているpasswordの値が`None`になっている原因を改めて確認しましょう。
Hint: Line26に注目。本当に`form.cleaned_data`の`password1`キーから値を取得できているか？
